export const collegeMajors = [
  "Accounting",
  "Aerospace Engineering",
  "African Studies",
  "Agricultural Sciences",
  "American Studies",
  "Anthropology",
  "Architecture",
  "Art History",
  "Astronomy",
  "Biochemistry",
  "Biology",
  "Biomedical Engineering",
  "Business Administration",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Classical Studies",
  "Communication Studies",
  "Computer Science",
  "Criminal Justice",
  "Cultural Studies",
  "Dance",
  "Dentistry",
  "Drama/Theatre Arts",
  "Earth Sciences",
  "Economics",
  "Education",
  "Electrical Engineering",
  "English Language and Literature",
  "Environmental Engineering",
  "Environmental Science",
  "Ethnic Studies",
  "Film",
  "Finance",
  "Forestry",
  "French",
  "Gender Studies",
  "Genetics",
  "Geography",
  "Geology",
  "German",
  "Graphic Design",
  "Health Administration",
  "History",
  "Hospitality Management",
  "Human Resources",
  "Industrial Engineering",
  "Information Technology",
  "Interior Design",
  "International Relations",
  "Journalism",
  "Kinesiology",
  "Law",
  "Linguistics",
  "Marketing",
  "Mathematics",
  "Mechanical Engineering",
  "Medicine",
  "Microbiology",
  "Music",
  "Nursing",
  "Nutrition",
  "Pharmacy",
  "Philosophy",
  "Physics",
  "Political Science",
  "Psychology",
  "Public Health",
  "Public Relations",
  "Religious Studies",
  "Sociology",
  "Spanish",
  "Special Education",
  "Statistics",
  "Urban Planning",
  "Veterinary Science",
  "Zoology"
]

export const slugify = (str: string) => {
  return str.toLowerCase().replace(/\s+/g, '-');
}